### ISSUE TITLE
Map layers in different boxes

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#211]
If the hamburger menu is closed, the network is "outside" of the base-map
<img width="50%" alt="Menu closed" src="https://user-images.githubusercontent.com/2158081/137765064-e796b553-640e-40d0-b9d5-9235be4b1bb3.png"> <img width="50%" alt="Menu opened" src="https://user-images.githubusercontent.com/2158081/137765055-b202e976-88f4-4480-9c54-11fb638fb6c5.png">

**Comment by vmarc** [comment]
Fixed in version 3.2.8, can be tested on [experimental](https://experimental.knooppuntnet.nl/).

**Comment by pyrog** [comment]
Thank you, this is fine.

There is still minor issues:

- in full screen mode, the map don't cover all the screen surface. There is a black rectangle at the top of the screen.

<img width="50%" alt="Full screen" src="https://user-images.githubusercontent.com/2158081/138636130-7a93b14e-0478-48b6-a64b-f429f0e0ef93.png">

- when scrolling the map, background and network layers sometime slip a bit. 
It seem that you display 2 maps on top of each other, not 1 map with 2 layers, is it ?

**Comment by vmarc** [comment]
@pyrog thanks for mentioning the problem with the map in fullscreen mode

I do not see the problem myself in the Chrome and Firefox browsers on my computer. I suspect this may be a Safari specific thing.

Do you also see the problem in this [OpenLayers example](https://openlayers.org/en/latest/examples/full-screen.html)?

Following the above example, I have added following css to knoopuntnet:

    .map:-webkit-full-screen {
      height: 100%;
      margin: 0;
    }

Do you still see the problem on [experimental](https://experimental.knooppuntnet.nl/fr/analysis/network/13305300/map) now?


Your hunch that 2 maps are displayed on top of eachother is correct. The background map uses [MapLibre](https://maplibre.org/), while the other layers are more 'pure' [OpenLayers](https://openlayers.org/).  This is not ideal, but I do not know a better solution at this moment.

**Comment by pyrog** [comment]
> Do you also see the problem in this OpenLayers example?

No the map cover all the screen 😄 

> Do you still see the problem on experimental now?

Yes, still have a black bar on top of the screen 😢 

> The background map uses MapLibre, while the other layers are more 'pure' OpenLayers. 

I didn't play with MapLibre, but with his MapBox ancestor.
I think it's possible to display many maps (even tiles like orthophotos)

I use Leaflet

**Comment by vmarc** [comment]
@pyrog for the black bar at the top of the screen: I have made some more css changes, could you try again on experimental?

**Comment by pyrog** [comment]
Better 😄 
Now white bar at the bottom (the background don't cover all the surface)

<img width="50%" alt="White bar" src="https://user-images.githubusercontent.com/2158081/138819368-aebfe196-8a8f-42d1-be24-f25c83bccf13.png">

**Comment by pyrog** [comment]
> I think it's possible to display many maps (even tiles like orthophotos)

With i.e. [Maputnik](https://maputnik.github.io) style editor, this is "easy" to edit osm-liberty-style and add sources like your hiking vector tiles or waymarkedtrails, orthophotos…

… and change dynamically the source according network found in URL (hiking, cycling, riding…)
… or i.e. hide background map labels

https://github.com/vmarc/knooppuntnet/blob/48e6d00dc72480dd0001c7e1cd85ff9c69f462a4/client/src/app/components/ol/layers/background-layer.ts#L17-L30

**Comment by vmarc** [comment]
@pyrog for the fullscreen issue: can you try on more time on experimental? 

On [browserstack](https://www.browserstack.com/live) it seems to work OK with Safari 14.1.

**Comment by vmarc** [comment]
@pyrog do you still see the problem with the white bar at the bottom in fullscreen?

**Comment by vmarc** [comment]
Tested on macOS/Safari: not possible to reproduce the problem.
